
# version: '1.29.2'
services:
  database:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'constman'   
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'      
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    command: --init-file /data/application/init.sql
    volumes:
      - './volumes/mysql:/var/lib/mysql'
      - './db.sql:/data/application/init.sql'
      # - "./db.sql:/docker-entrypoint-initdb.d/1.sql"