name: dartback
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.3'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0

dependencies: 
  shelf: ^1.3.1
  shelf_router: ^1.1.3
  dart_jsonwebtoken: ^2.4.1
  mysql_client: ^0.0.21
  password_dart: ^2.0.1
